#!/usr/bin/env bash
m="\e[0;31m" # merah
k="\e[0;33m" # kuning
h="\e[0;32m" # hijau
b="\e[0;34m" # biru
lm="\e[1;31m" # merah terang
lk="\e[1;33m" # kuning terang
lh="\e[1;32m" # hijau terang
lb="\e[1;34m" # langit biru
n="\e[0m" # netral
w="\e[1;37m" # putih tebal

clear

if ! msfconsole -v COMMAND &> /dev/null
then
    echo "msf could not be found"
else
  xterm -T "☣ INSTALL SEARCHSPLOIT ☣" -geometry 100x30 -e "sudo apt-get install msfconsole -y"
  if ! msfconsole -v COMMAND &> /dev/null
  then
      echo "Failed install"
  else
    echo "sucess"
fi
